# 0 "../../../src/Game/functions.h"
# 1 "/home/adam/Downloads/Hiigara-wasm/Hiigara-wasm/Linux/src/Game//"
# 0 "<built-in>"
# 0 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 0 "<command-line>" 2
# 1 "../../../src/Game/functions.h"
# 1 "../../../src/Game/wrap_types.h" 1
# 2 "../../../src/Game/functions.h" 2
# 1 "../../../src/Game/wrap.h" 1
# 9 "../../../src/Game/wrap.h"
static inline memsize do_get_arg(Effect *effect, struct etgeffectstatic *stat, etgfunctioncall *opcode, udword index)
{
    memsize param = opcode->parameter[index].param;

    switch (opcode->parameter[index].type)
    {
        case EVT_Constant:
            break;
        case EVT_Label:
            dbgAssertOrIgnore(FALSE);
            break;
        case EVT_ConstLabel:
            param = (memsize)stat->constData + param;
            break;
        case EVT_VarLabel:
            param = (memsize)effect->variable + param;
            break;
        default:
            param = *((memsize *)(effect->variable + param));
            break;
    }
    return param;
}
# 3 "../../../src/Game/functions.h" 2


    memsize wrap_etgSetDefaults(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { void (*func_ptr)(void) = opcode->function; func_ptr(); return 0; }
    memsize wrap_etgSetDrag(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetScale(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetXYZScale(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); real32 var2 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 2)); void (*func_ptr)(real32, real32, real32) = (void (*)(real32, real32, real32)) opcode->function; func_ptr(var0, var1, var2); return 0; }
    memsize wrap_partSetScaleDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetDeltaScale(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetDeltaScaleDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetOffsetLOF(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetOffsetR(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetOffsetTheta(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetOffsetArray(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); void (*func_ptr)(memsize) = (void (*)(memsize)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetDeltaLOF(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetDeltaLOFDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetDeltaR(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(real32, real32) = (void (*)(real32, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partSetDeltaRDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(real32, real32) = (void (*)(real32, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partSetVelLOF(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetVelLOFDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetVelR(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetVelRDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }

    memsize wrap_partSetAng(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetDeltaVelLOF(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetDeltaVelLOFDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetDeltaVelR(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetDeltaVelRDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetAngDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetAngDelta(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetAngDeltaDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_etgSetColor(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); void (*func_ptr)(memsize) = (void (*)(memsize)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetColorDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); real32 var2 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 2)); void (*func_ptr)(real32, real32, real32) = (void (*)(real32, real32, real32)) opcode->function; func_ptr(var0, var1, var2); return 0; }
    memsize wrap_partSetDeltaColor(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); real32 var2 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 2)); void (*func_ptr)(real32, real32, real32) = (void (*)(real32, real32, real32)) opcode->function; func_ptr(var0, var1, var2); return 0; }
    memsize wrap_partSetDeltaColorDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); real32 var2 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 2)); void (*func_ptr)(real32, real32, real32) = (void (*)(real32, real32, real32)) opcode->function; func_ptr(var0, var1, var2); return 0; }
    memsize wrap_etgSetColorA(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); void (*func_ptr)(memsize) = (void (*)(memsize)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetColorADist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); real32 var2 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 2)); real32 var3 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 3)); void (*func_ptr)(real32, real32, real32, real32) = (void (*)(real32, real32, real32, real32)) opcode->function; func_ptr(var0, var1, var2, var3); return 0; }
    memsize wrap_partSetDeltaColorA(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); real32 var2 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 2)); real32 var3 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 3)); void (*func_ptr)(real32, real32, real32, real32) = (void (*)(real32, real32, real32, real32)) opcode->function; func_ptr(var0, var1, var2, var3); return 0; }
    memsize wrap_partSetDeltaColorADist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); real32 var2 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 2)); real32 var3 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 3)); void (*func_ptr)(real32, real32, real32, real32) = (void (*)(real32, real32, real32, real32)) opcode->function; func_ptr(var0, var1, var2, var3); return 0; }
    memsize wrap_partSetColorBias(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); real32 var2 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 2)); void (*func_ptr)(real32, real32, real32) = (void (*)(real32, real32, real32)) opcode->function; func_ptr(var0, var1, var2); return 0; }
    memsize wrap_partSetColorBiasDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); real32 var2 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 2)); void (*func_ptr)(real32, real32, real32) = (void (*)(real32, real32, real32)) opcode->function; func_ptr(var0, var1, var2); return 0; }
    memsize wrap_partSetLighting(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); void (*func_ptr)(memsize) = (void (*)(memsize)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetIsWorldspace(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); void (*func_ptr)(memsize) = (void (*)(memsize)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetVelocityInWorldSpace(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); void (*func_ptr)(memsize) = (void (*)(memsize)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetIllum(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetIllumDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetDeltaIllum(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetDeltaIllumDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetLifespan(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetLifespanDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetWaitspan(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetWaitspanDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetLength(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetLengthDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetDeltaLength(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetDeltaLengthDist(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetSlices(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); void (*func_ptr)(memsize) = (void (*)(memsize)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetTumble(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); real32 var2 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 2)); void (*func_ptr)(real32, real32, real32) = (void (*)(real32, real32, real32)) opcode->function; func_ptr(var0, var1, var2); return 0; }
    memsize wrap_partSetDeltaTumble(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); real32 var2 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 2)); void (*func_ptr)(real32, real32, real32) = (void (*)(real32, real32, real32)) opcode->function; func_ptr(var0, var1, var2); return 0; }
    memsize wrap_etgSetAnimation(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); memsize var2 = do_get_arg(effect, stat, opcode, 2); void (*func_ptr)(memsize, real32, memsize) = (void (*)(memsize, real32, memsize)) opcode->function; func_ptr(var0, var1, var2); return 0; }
    memsize wrap_etgSetMorphAnimation(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); memsize var2 = do_get_arg(effect, stat, opcode, 2); void (*func_ptr)(memsize, real32, memsize) = (void (*)(memsize, real32, memsize)) opcode->function; func_ptr(var0, var1, var2); return 0; }
    memsize wrap_partSetMeshStartFrame(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetFramerate(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetLoopFlag(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); void (*func_ptr)(memsize) = (void (*)(memsize)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetStartFrame(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); void (*func_ptr)(memsize) = (void (*)(memsize)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetAlphaMode(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); void (*func_ptr)(memsize) = (void (*)(memsize)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_etgSetSpecular(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetColorScheme(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); void (*func_ptr)(memsize) = (void (*)(memsize)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetTrueBillboard(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); void (*func_ptr)(memsize) = (void (*)(memsize)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_partSetPseudoBillboard(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); void (*func_ptr)(memsize) = (void (*)(memsize)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_etgSetDepthWrite(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); void (*func_ptr)(memsize) = (void (*)(memsize)) opcode->function; func_ptr(var0); return 0; }


    memsize wrap_etgModifyDrag(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(memsize, real32) = (void (*)(memsize, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyScale(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(memsize, real32) = (void (*)(memsize, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyDeltaScale(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(memsize, real32) = (void (*)(memsize, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyDeltaLength(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(memsize, real32) = (void (*)(memsize, real32)) opcode->function; func_ptr(var0, var1); return 0; }

    memsize wrap_partModifyColorC(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); void (*func_ptr)(memsize, memsize) = (void (*)(memsize, memsize)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyColorBias(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); real32 var2 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 2)); real32 var3 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 3)); void (*func_ptr)(memsize, real32, real32, real32) = (void (*)(memsize, real32, real32, real32)) opcode->function; func_ptr(var0, var1, var2, var3); return 0; }
    memsize wrap_partModifyAddColor(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); void (*func_ptr)(memsize, memsize) = (void (*)(memsize, memsize)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyDeltaColor(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); real32 var2 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 2)); real32 var3 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 3)); real32 var4 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 4)); void (*func_ptr)(memsize, real32, real32, real32, real32) = (void (*)(memsize, real32, real32, real32, real32)) opcode->function; func_ptr(var0, var1, var2, var3, var4); return 0; }
    memsize wrap_partModifyLighting(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(memsize, real32) = (void (*)(memsize, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyIllum(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(memsize, real32) = (void (*)(memsize, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyDeltaIllum(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(memsize, real32) = (void (*)(memsize, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyLifespan(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(memsize, real32) = (void (*)(memsize, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyAnimation(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); void (*func_ptr)(memsize, memsize) = (void (*)(memsize, memsize)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyFramerate(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(memsize, real32) = (void (*)(memsize, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyVelLOF(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(memsize, real32) = (void (*)(memsize, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyDeltaVelLOF(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(memsize, real32) = (void (*)(memsize, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyVelR(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(memsize, real32) = (void (*)(memsize, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyDeltaVelR(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(memsize, real32) = (void (*)(memsize, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyMesh(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(memsize, real32) = (void (*)(memsize, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyMorph(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); void (*func_ptr)(memsize, memsize) = (void (*)(memsize, memsize)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyMorphFramerate(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(memsize, real32) = (void (*)(memsize, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyLength(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(memsize, real32) = (void (*)(memsize, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyExponent(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(memsize, real32) = (void (*)(memsize, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyColorScheme(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); void (*func_ptr)(memsize, memsize) = (void (*)(memsize, memsize)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_partModifyAlphaMode(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); void (*func_ptr)(memsize, memsize) = (void (*)(memsize, memsize)) opcode->function; func_ptr(var0, var1); return 0; }

    memsize wrap_partModifyPseudoBillboard(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); void (*func_ptr)(memsize, memsize) = (void (*)(memsize, memsize)) opcode->function; func_ptr(var0, var1); return 0; }


    memsize wrap_etgCreateSprites(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); memsize (*func_ptr)(void *, memsize, memsize) = (memsize (*)(void *, memsize, memsize)) opcode->function; return func_ptr(effect, var0, var1); }
    memsize wrap_etgCreateCircles(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); memsize (*func_ptr)(void *, memsize, memsize) = (memsize (*)(void *, memsize, memsize)) opcode->function; return func_ptr(effect, var0, var1); }
    memsize wrap_etgCreatePoints(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); memsize (*func_ptr)(void *, memsize, memsize) = (memsize (*)(void *, memsize, memsize)) opcode->function; return func_ptr(effect, var0, var1); }
    memsize wrap_etgCreateLines(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); memsize (*func_ptr)(void *, memsize, memsize) = (memsize (*)(void *, memsize, memsize)) opcode->function; return func_ptr(effect, var0, var1); }
    memsize wrap_etgCreateMeshes(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); memsize (*func_ptr)(void *, memsize, memsize) = (memsize (*)(void *, memsize, memsize)) opcode->function; return func_ptr(effect, var0, var1); }


    memsize wrap_etgInc(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize (*func_ptr)(memsize) = (memsize (*)(memsize)) opcode->function; return func_ptr(var0); }
    memsize wrap_etgDec(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize (*func_ptr)(memsize) = (memsize (*)(memsize)) opcode->function; return func_ptr(var0); }
    memsize wrap_etgFdiv(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); udword (*func_ptr)(real32, real32) = (udword (*)(real32, real32)) opcode->function; return func_ptr(var0, var1); }
    memsize wrap_etgFmult(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); udword (*func_ptr)(real32, real32) = (udword (*)(real32, real32)) opcode->function; return func_ptr(var0, var1); }
    memsize wrap_etgFadd(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); udword (*func_ptr)(real32, real32) = (udword (*)(real32, real32)) opcode->function; return func_ptr(var0, var1); }
    memsize wrap_etgFsub(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); udword (*func_ptr)(real32, real32) = (udword (*)(real32, real32)) opcode->function; return func_ptr(var0, var1); }
    memsize wrap_etgDiv(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); memsize (*func_ptr)(memsize, memsize) = (memsize (*)(memsize, memsize)) opcode->function; return func_ptr(var0, var1); }
    memsize wrap_etgMult(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); memsize (*func_ptr)(memsize, memsize) = (memsize (*)(memsize, memsize)) opcode->function; return func_ptr(var0, var1); }
    memsize wrap_etgAdd(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); memsize (*func_ptr)(memsize, memsize) = (memsize (*)(memsize, memsize)) opcode->function; return func_ptr(var0, var1); }
    memsize wrap_etgSub(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); memsize (*func_ptr)(memsize, memsize) = (memsize (*)(memsize, memsize)) opcode->function; return func_ptr(var0, var1); }
    memsize wrap_etgSin(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); udword (*func_ptr)(real32) = (udword (*)(real32)) opcode->function; return func_ptr(var0); }
    memsize wrap_etgCos(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); udword (*func_ptr)(real32) = (udword (*)(real32)) opcode->function; return func_ptr(var0); }
    memsize wrap_etgFRandom(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); udword (*func_ptr)(real32, real32) = (udword (*)(real32, real32)) opcode->function; return func_ptr(var0, var1); }
    memsize wrap_etgIRandom(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); memsize (*func_ptr)(memsize, memsize) = (memsize (*)(memsize, memsize)) opcode->function; return func_ptr(var0, var1); }
    memsize wrap_etgCRandom(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); memsize var2 = do_get_arg(effect, stat, opcode, 2); memsize var3 = do_get_arg(effect, stat, opcode, 3); memsize var4 = do_get_arg(effect, stat, opcode, 4); memsize var5 = do_get_arg(effect, stat, opcode, 5); memsize (*func_ptr)(memsize, memsize, memsize, memsize, memsize, memsize) = (memsize (*)(memsize, memsize, memsize, memsize, memsize, memsize)) opcode->function; return func_ptr(var0, var1, var2, var3, var4, var5); }
    memsize wrap_etgCARandom(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); memsize var2 = do_get_arg(effect, stat, opcode, 2); memsize var3 = do_get_arg(effect, stat, opcode, 3); memsize var4 = do_get_arg(effect, stat, opcode, 4); memsize var5 = do_get_arg(effect, stat, opcode, 5); memsize var6 = do_get_arg(effect, stat, opcode, 6); memsize var7 = do_get_arg(effect, stat, opcode, 7); memsize (*func_ptr)(memsize, memsize, memsize, memsize, memsize, memsize, memsize, memsize) = (memsize (*)(memsize, memsize, memsize, memsize, memsize, memsize, memsize, memsize)) opcode->function; return func_ptr(var0, var1, var2, var3, var4, var5, var6, var7); }


    memsize wrap_etgParentShipDelete(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { void (*func_ptr)(void *) = (void (*)(void *)) opcode->function; func_ptr(effect); return 0; }
    memsize wrap_etgParentShipHide(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { void (*func_ptr)(void *) = (void (*)(void *)) opcode->function; func_ptr(effect); return 0; }
    memsize wrap_soundEffect(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize (*func_ptr)(void *, memsize) = (memsize (*)(void *, memsize)) opcode->function; return func_ptr(effect, var0); }
    memsize wrap_etgChatterEventPlay(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); void (*func_ptr)(void *, memsize) = (void (*)(void *, memsize)) opcode->function; func_ptr(effect, var0); return 0; }
    memsize wrap_etgDeathCriesPlay(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { void (*func_ptr)(void *) = (void (*)(void *)) opcode->function; func_ptr(effect); return 0; }
    memsize wrap_etgOwnerColorSchemeGet(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { udword (*func_ptr)(void *) = (udword (*)(void *)) opcode->function; return func_ptr(effect); }
    memsize wrap_etgEffectVelocityGet(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { udword (*func_ptr)(void *) = (udword (*)(void *)) opcode->function; return func_ptr(effect); }
    memsize wrap_etgDamageDone(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { void (*func_ptr)(void *) = (void (*)(void *)) opcode->function; func_ptr(effect); return 0; }


    memsize wrap_etgEffOffsetLOF(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_etgEffChangeLOF(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(real32, real32) = (void (*)(real32, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_etgEffOffsetR(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); void (*func_ptr)(real32, real32) = (void (*)(real32, real32)) opcode->function; func_ptr(var0, var1); return 0; }
    memsize wrap_etgEffOffsetXYZ(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); real32 var2 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 2)); void (*func_ptr)(real32, real32, real32) = (void (*)(real32, real32, real32)) opcode->function; func_ptr(var0, var1, var2); return 0; }
    memsize wrap_etgEffOffsetVelLOF(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_etgEffOffsetSpin(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_etgEffOffsetTime(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_etgEffOffsetDrag(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(void *, real32) = (void (*)(void *, real32)) opcode->function; func_ptr(effect, var0); return 0; }
    memsize wrap_etgEffDrag(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(real32) = (void (*)(real32)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_etgEffDefaults(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { void (*func_ptr)(void) = opcode->function; func_ptr(); return 0; }
    memsize wrap_etgEffAttachParent(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); void (*func_ptr)(memsize) = (void (*)(memsize)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_etgEffSpin(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); void (*func_ptr)(memsize) = (void (*)(memsize)) opcode->function; func_ptr(var0); return 0; }
    memsize wrap_etgEffDeltaSpin(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); void (*func_ptr)(memsize) = (void (*)(memsize)) opcode->function; func_ptr(var0); return 0; }


    memsize wrap_etgThisOffsetXYZ(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); real32 var2 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 2)); void (*func_ptr)(void *, real32, real32, real32) = (void (*)(void *, real32, real32, real32)) opcode->function; func_ptr(effect, var0, var1, var2); return 0; }
    memsize wrap_etgThisScaleVelocity(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(void *, real32) = (void (*)(void *, real32)) opcode->function; func_ptr(effect, var0); return 0; }
    memsize wrap_etgThisOffsetSpin(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(void *, real32) = (void (*)(void *, real32)) opcode->function; func_ptr(effect, var0); return 0; }
    memsize wrap_etgThisOffsetDeltaSpin(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(void *, real32) = (void (*)(void *, real32)) opcode->function; func_ptr(effect, var0); return 0; }
    memsize wrap_etgThisOffsetTime(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(void *, real32) = (void (*)(void *, real32)) opcode->function; func_ptr(effect, var0); return 0; }
    memsize wrap_etgThisSetDrag(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); void (*func_ptr)(void *, real32) = (void (*)(void *, real32)) opcode->function; func_ptr(effect, var0); return 0; }


    memsize wrap_etgFloat2Int(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); memsize (*func_ptr)(real32) = (memsize (*)(real32)) opcode->function; return func_ptr(var0); }
    memsize wrap_etgInt2Float(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); udword (*func_ptr)(memsize) = (udword (*)(memsize)) opcode->function; return func_ptr(var0); }
    memsize wrap_etgInts2Color(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); memsize var2 = do_get_arg(effect, stat, opcode, 2); memsize (*func_ptr)(memsize, memsize, memsize) = (memsize (*)(memsize, memsize, memsize)) opcode->function; return func_ptr(var0, var1, var2); }
    memsize wrap_etgInts2ColorA(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { memsize var0 = do_get_arg(effect, stat, opcode, 0); memsize var1 = do_get_arg(effect, stat, opcode, 1); memsize var2 = do_get_arg(effect, stat, opcode, 2); memsize var3 = do_get_arg(effect, stat, opcode, 3); memsize (*func_ptr)(memsize, memsize, memsize, memsize) = (memsize (*)(memsize, memsize, memsize, memsize)) opcode->function; return func_ptr(var0, var1, var2, var3); }
    memsize wrap_etgFloats2Color(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); real32 var2 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 2)); memsize (*func_ptr)(real32, real32, real32) = (memsize (*)(real32, real32, real32)) opcode->function; return func_ptr(var0, var1, var2); }
    memsize wrap_etgFloats2ColorA(Effect *effect, struct etgeffectstatic *stat ,etgfunctioncall *opcode) { real32 var0 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 0)); real32 var1 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 1)); real32 var2 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 2)); real32 var3 = MemsizeToReal32(do_get_arg(effect, stat, opcode, 3)); memsize (*func_ptr)(real32, real32, real32, real32) = (memsize (*)(real32, real32, real32, real32)) opcode->function; return func_ptr(var0, var1, var2, var3); }
